name: Commit hash placeholder
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Find and Replace
      uses: shitiomatic/str-replace@master
      with:
        find: "{current-commit-id}"
        replace: $(git rev-parse HEAD)
        include: "(?i).*\\.md$"
