name: Commit hash placeholder
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
     
    - name: Declare some variables
      id: vars
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse HEAD)"

    - name: Another step
      run: |
        echo "Sha: ${{ steps.vars.outputs.sha_short }}"
    
    - name: Declare SHA variable
      id: vars2
      shell: bash
      run: |
          echo "aaa"
          echo "::set-output name=sha::$(git rev-parse HEAD)"
          echo "sha: ${{ steps.vars.outputs.sha }}"
          
    - name: Find and Replace
      uses: shitiomatic/str-replace@master
      with:
        find: "{current-commit-id}"
        replace: "${{ steps.vars.outputs.sha }}"
        include: "(?i).*\\.md$"


