name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "hello"
          replace: "world"
          include: "README.md" # Will match all README.md files in any nested directory

# name: Commit hash placeholder
# on: [push, pull_request]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master
     
#     - name: Declare SHA variable
#       id: vars
#       shell: bash
#       run: |
#           echo "::set-output name=sha::$(git rev-parse HEAD)"
#           echo "sha a: ${{ steps.vars.outputs.sha }}"
#           echo "sha b: $(git rev-parse HEAD)"
          
#     - name: Find and Replace
#       uses: jacobtomlinson/gha-find-replace@master
#       with:
#         find: "{current-commit-id}"
#         replace: "${{ steps.vars.outputs.sha }}"
#         include: "(?i).*\\.md$"


