name: Commit hash placeholder
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Declare SHA variable
      run: |
          echo "::set-output name=sha::$(git rev-parse HEAD)"
          
    - name: Find and Replace
      uses: shitiomatic/str-replace@master
      with:
        find: "{current-commit-id}"
        replace: ${{ steps.vars.outputs.sha }}
        include: "(?i).*\\.md$"


